### PR TITLE
First stab at addressing per-second billing

### PR DESCRIPTION
**Pull request by QuinnyPig**

### CODE REVIEW

**Comment by bgdnlp** [comment]
* The Scalr link returns 404 for me. Is this the new way: https://github.com/Scalr/installer-ng ?

* Would it be worth mentioning that hourly billing only applies to dedicated instances now? Assuming that that's true.

**Comment by QuinnyPig** [comment]
Hah, good find. I didn't touch the link yet. Will fix while I'm here.

**Comment by QuinnyPig** [comment]
> Would it be worth mentioning that hourly billing only applies to dedicated instances now? Assuming that that's true.

Nope-- it also applies to Windows instances, and per-hour licensed enterprise Linux instances. 

I suggest merging this one, and I'll come up with a separate section on per-second billing this week.

**Comment by bgdnlp** [comment]
FWIW, agree with the merge.

**Comment by ThanosBaskous** [comment]
Good cleanup @QuinnyPig. Thanks for the review @bgdnlp. I agree with a merge on this + separate section to follow.

**Pull request merged**
