### PR TITLE
Add ALB limitation

### PR DESCRIPTION
**Pull request by gabinante**
ALBs now support SNI, so this piece of the guide was wrong. However, they do have an undocumented limitation of 25 certs per ALB. 

Also, my editor aggressively removes trailing whitespaces. Hope this isn't a problem - if it is, I can redo my commit.

### CODE REVIEW

**Comment by gabinante** [comment]
libraries.io is down so awesomebot is failing to check this link: https://libraries.io/github/awslabs/aws-iot-demo-for-danbo

**Comment by jlevy** [comment]
LGTM! Thanks @gabinante . @ThanosBaskous is a load balancing expert so let's get his review for merge.

**Comment by jlevy** [comment]
Also added a link on the SNI support update and restored the "undocumented" emoji.

**Comment by ThanosBaskous** [comment]
LGTM as well. Thanks @gabinante  (and @jlevy)!

**Pull request merged**
