### PR TITLE
Sunsetting S3 Reduced Redundancy

### PR DESCRIPTION
**Pull request by QuinnyPig**

### CODE REVIEW

**Comment by ThanosBaskous** [comment]
Great update, thanks @QuinnyPig!

**Comment by FernandoMiguel** [comment]
@QuinnyPig do you have a public source for this ?
thanks for the heads up, just checked the prices and they are indeed pointing to being depreciated

**Comment by QuinnyPig** [comment]
They no longer include it when discussing S3 options; https://aws.amazon.com/blogs/aws/category/amazon-s3/ mentions three classes, not four.

**Comment by QuinnyPig** [comment]
Er, https://aws.amazon.com/blogs/aws/s3-storage-management-update-analytics-object-tagging-inventory-and-metrics/

**Pull request merged**
