### PR TITLE
Adding CenturyLink services

### PR DESCRIPTION
**Pull request by jorn-k**
CLC  (CenturyLink Cloud; former Tier3 offering) often considered in top 5 by analysts and pundits; should be included for comparison.

### CODE REVIEW

**Comment by jlevy** [comment]
Thanks for the suggestions.

Seems like CenturyLink is a significant provider, but I'm not sure it's at a level where it'd be mentioned between Azure and Rackspace. Do you have some market sector data you could share? The Gartner report in #111 may help with this.

Also, do you mind disclosing if you have an affiliation with CenturyLink? The cloud ecosystem is full of competitors so we're looking to have a process where we disclose/review this kind of thing thoughtfully.

**Comment by rjhintz** [comment]
Centurylink fell out of the top right in Gartner's Magic Quadrant in 2016 and has widely been reported to be trying to exit their Saavis acquisiton. News today is that they're acquiring Level3, so more telecom, less XaaS as a portion of their biz. 

I don't strong feelings about including anyone, besides Google and Azure, but the rest seem niche players at best.

**Comment by QuinnyPig** [comment]
Suggest closing this; this is the first place I've ever seen CenturyLink offering something that isn't bandwidth.

**Comment by DavidTPate** [comment]
I agree that I think this shouldn't be included and I would prefer to just reference something such as Gartner's Magic Quadrant to keep this guide more agnostic. Ideally, we would remove the "Rackspace" portion as well or at the very least only mention those that are in the top right of Gartner (which I expect includes Rackspace among others).

**Comment by QuinnyPig** [comment]
Closing for now; feel free to continue the conversation / revisit this as the landscape changes.

**Pull request closed without merging**
