### PR TITLE
Update DynamoDB Titan Graph Support

### PR DESCRIPTION
**Pull request by kimschmidtsbrain**

### CODE REVIEW

**Comment by lynnlangit** [comment]
My experience is that this very much an [edge use case](https://groups.google.com/forum/#!msg/aureliusgraphs/R0RJnvVbgCs/vkYEsXD3HgAJ) (if used at all), rather clients tend to prefer a dedicated graph database, such as Neo4j on EC2.

**Comment by kimschmidtsbrain** [comment]
Thank you!

Although that might be true, should we add the capability?

Sincerely,

Kim Schmidt
949-735-8505
@DataLeader, @WearableQueen
https://www.linkedin.com/in/kimschmidt1

**Comment by lynnlangit** [comment]
I would say we should NOT add it due to it's very limited use in the real world.

**Comment by kimschmidtsbrain** [comment]
OK!

We want to keep things relevant to the real world.

Sincerely,

Kim Schmidt
949-735-8505
@DataLeader, @WearableQueen
https://www.linkedin.com/in/kimschmidt1
https://kimschmidtsbrain.com/
https://awskimschmidt.com/  <https://awskimschmidt.com/>

**Comment by ThanosBaskous** [comment]
Thanks for your submission, @kimschmidtsbrain. I agree with @lynnlangit on this one - I'm going to close but if you think it warrants further discussion happy to keep talking here or in Slack.

**Comment by kimschmidtsbrain** [comment]
NP. Get it :-)

Sincerely,

Kim Schmidt
949-735-8505
@DataLeader, @WearableQueen
https://www.linkedin.com/in/kimschmidt1
https://kimschmidtsbrain.com/
https://awskimschmidt.com/  <https://awskimschmidt.com/>

**Pull request closed without merging**
