### PR TITLE
Never suggest us-west-1; it's expensive and massively capacity constrained.

### PR DESCRIPTION
**Pull request by QuinnyPig**

### CODE REVIEW

**Comment by ThanosBaskous** [comment]
Never is a strong word - there are good reasons to be in us-west-1. For example, when you need low latencies to ad exchanges, which themselves have sprung up in and around us-west-1. I'd prefer to add more nuance to the recommendation rather than remove us-west-1 altogether. Thoughts?

**Comment by bgdnlp** [comment]
I'd scrap suggesting a region completely. Suggest considering latency (don't set up in US if your operations are in Europe) and pricing (some regions are more expensive than others, even in similar locations, for example us-west-1 vs us-west-2) and let the reader do their own research. Any region suggestion might be invalid in 6 months if Amazon decides so anyway.

**Comment by ThanosBaskous** [comment]
Good suggestions, @bgdnlp, I'd be on board with framing it that way as well.

**Comment by QuinnyPig** [comment]
Reframed; what do you think now?

**Comment by ThanosBaskous** [comment]
That looks great to me - thanks @QuinnyPig!

**Pull request merged**
