### PR TITLE
Fixups and Markdown formatting

### PR DESCRIPTION
**Pull request by jlevy**
Seems like https://github.com/shurcooL/markdownfmt is the best option to keep things consistent. 

I also looked at https://github.com/slang800/tidy-markdown (which is nice since it has an Atom plugin) but it has quirks around nested itemized lists (some are condensed and some are loose), and it deliberately strips smart quotes, both of which seemed a bit questionable.

### CODE REVIEW

**Comment by ThanosBaskous** [comment]
I'm on board with a formatter. @jlevy what do you think about not _requiring_ contributors to run it before every submission but instead, one of us occasionally running it to clean things up?

**Comment by jlevy** [comment]
Yeah, agreed, good point. Obstacles to contributing should be minimal.

**Comment by ThanosBaskous** [comment]
👍 Looks good to me, thanks @jlevy.

**Comment by jlevy** [comment]
Linking the tidy-markdown lists issue, for reference.
https://github.com/slang800/tidy-markdown/issues/17

**Pull request merged**
