### PR TITLE
Reword how ACM domain validation works

### PR DESCRIPTION
**Pull request by QuinnyPig**
Domain validation is the superior / recommended method; putting it first instead of as an afterthought.

### CODE REVIEW

**Comment by paulwakeford** [comment]
The way this is worked sounds like DNS validation is only supported with R53. Perhaps reword to: 'If the zone lives within Route 53 and the user has access, the necessary record can be added in the console via a single click during the certificate request process. If the zone is not within Route53 the user is required to update DNS manually. This is still preferred to the second way, which requires more user interaction...'

**Comment by QuinnyPig** [comment]
This was updated. Thanks, @paulwakeford. Good to merge?

**Comment by paulwakeford** [comment]
Minor typo :'If the zone is not within Route5 3'

**Comment by QuinnyPig** [comment]
There I fixed it

**Comment by QuinnyPig** [comment]
@paulwakeford Happy for me to merge this?

**Comment by paulwakeford** [comment]
Ecstatic!

**Pull request merged**
