### PR TITLE
DynamoDB gotcha: moment-in-time backups

### PR DESCRIPTION
**Pull request by trenton**
This has surprised more than one person I've talked to, so I thought I'd contribute it here.

Full disclosure: I'm a developer at Amazon.

### CODE REVIEW

**Comment by ThanosBaskous** [comment]
Great addition, @trenton, and thanks for the disclosure. LGTM.

Bouncing to @jlevy or @QuinnyPig for second review before merging.

**Comment by QuinnyPig** [comment]
Looks good-- thanks for the contribution!

**Comment by trenton** [comment]
Np. This project has pulled together some real gems. I've shared it among the developers I worked with. Thanks for _your_ contributions.

**Comment by ThanosBaskous** [comment]
Thanks! 👍

**Comment by jlevy** [comment]
Thanks @trenton and great addition. We welcome contributions from anyone, but just make sure submitters disclose relevant details and that PRs get reviewed by the editors. So feel free to keep items coming. :)

**Pull request merged**
