### PR TITLE
Amazon Linux package versioning notes

### LINKED ISSUE #6: Amazon Linux Yum Repo update tradeoffs / gotchas

### PR DESCRIPTION
**Pull request by ThanosBaskous**
Resolves #6.

### CODE REVIEW

**Comment by jlevy** [comment]
Looks good!
Perhaps this be condensed into bullet point, since the two links are the same target? And minor, but I've tried to apply Unicode punctuation for consistency:
 'latest' -> “latest”
- -> —
Amazon's -> Amazon’s

**Comment by jlevy** [comment]
Oh, I take it back re punctuation on 'latest' since it's a literal string. :)

**Comment by ThanosBaskous** [comment]
@jlevy good notes, thanks. I combined the bullets and fixed the punctuation characters.

**Comment by jlevy** [comment]
👍

**Pull request merged**
