### PR TITLE
Added Last Week in AWS to further reading section

### PR DESCRIPTION
**Pull request by QuinnyPig**
Note that this requires a bit of scrutiny; I'm the editor of the newsletter in question, so my bias is rather clear!

### CODE REVIEW

**Comment by ThanosBaskous** [comment]
Thanks for calling out your association @QuinnyPig - I think that a link out to "Last Week in AWS" is a great addition to the guide. I'm supportive of this change - will wait for one more editor to +1 before one of us merges.

**Comment by jlevy** [comment]
I'm in favor too — it's been well received by folks here, and seems there's no other newsletter like it.

**Comment by jlevy** [comment]
Given we usually leave "neutrality" ones open a little longer in case there are comments, I'll wait until Mon to merge this.

**Comment by QuinnyPig** [comment]
@jlevy It's been two Mondays. :)

**Comment by ThanosBaskous** [comment]
👍 I think that we've provided enough time for comment on this.

**Pull request merged**
