### PR TITLE
Added new tip for APIG that I got from AWS support

### PR DESCRIPTION
**Pull request by dijitalmunky**
This is a tip I received from AWS support when we were experiencing a 400 - Bad request being seemingly translated to a 504 - Gateway timeout.  Turns out that our server was doing chunked encoding transfers on the payload for the 400 and was not terminating the last chunk correctly.

### CODE REVIEW

**Comment by ThanosBaskous** [comment]
This is a good tip - thank you for submitting it, @dijitalmunky!

I have a few nits on style but will address them myself in a followup PR.

**Comment by dijitalmunky** [comment]
Yeah, I noticed that formatting was a little all over as well. Did I miss a published markdown formatting guide for this project?

**Comment by ThanosBaskous** [comment]
Hi @dijitalmunky - there is some style and convention information in CONTRIBUTING.md (which is worth checking out if you haven't), but it could probably be more comprehensive.

**Comment by dijitalmunky** [comment]
Whoops, I missed that part of the guide.  My bad.  I'll be sure to look through it before my next PR :)

**Pull request merged**
