### PR TITLE
Update diagram for data transfer

### PR DESCRIPTION
**Pull request by QuinnyPig**

### CODE REVIEW

**Comment by ThanosBaskous** [comment]
LGTM - suggest waiting for a review by @jlevy as well.

**Comment by ThanosBaskous** [comment]
Thanks for updating this, @QuinnyPig!

**Comment by QuinnyPig** [comment]
@jlevy to the courtesy phone, please.

**Comment by ThanosBaskous** [comment]
I'm going to merge this - if future reviewers find anything wrong in the network transfer costs diagram, please file a new issue. Thanks again for updating this, @QuinnyPig!

**Comment by jlevy** [comment]
Sorry for delay! LGTM. 👍

**Pull request merged**
