### PR TITLE
API Gateway limitation

### PR DESCRIPTION
**Pull request by lbailly**
Add new API Gateway limitation

### CODE REVIEW

**Comment by QuinnyPig** [comment]
Great find! Have an official citation you can link against in the guide for when this invariably changes in the future? :-)

**Comment by QuinnyPig** [comment]
@lbailly Just checking up on this one. Thanks for the contribution; any luck finding a citation?

**Comment by cristim** [comment]
I think this limitation may have a workaround now that the API gateway can be configured without the Cloudfront distribution layer:

- https://aws.amazon.com/about-aws/whats-new/2017/11/amazon-api-gateway-supports-regional-api-endpoints/

- https://docs.aws.amazon.com/apigateway/latest/developerguide/create-regional-api.html

**Comment by ThanosBaskous** [comment]
@lbailly - thanks for your submission. Can you confirm or disconfirm the original limitation based on the links in @cristim's comment?

**Comment by QuinnyPig** [comment]
Closing for now pending further review.

**Pull request closed without merging**
