### PR TITLE
Added ALB and CLB  gotchas about 2048 bit ssl cert

### PR DESCRIPTION
**Pull request by Bizzelicious**

### CODE REVIEW

**Comment by jlevy** [comment]
+ @ThanosBaskous for topic review at once.

**Comment by ThanosBaskous** [comment]
The content here is good -  thanks @Bizzelicious. I agree with @jlevy that it should be consolidated into the general load balancer section. Please see phrasing suggestion in #281 as well.

**Comment by Bizzelicious** [comment]
You can now have 4096 certs on CLBs and ALBs. However, CloudFront doesn't support it yet so #282 is still open.

**Comment by jlevy** [comment]
OK, thanks @Bizzelicious for following up!

**Pull request closed without merging**
