### PR TITLE
[Device Farm] Add information about long waiting time and a way to minimize it

### PR DESCRIPTION
**Pull request by artemnikitin**

### CODE REVIEW

**Comment by artemnikitin** [comment]
CI fail is a little bit strange. Not sure if it's because of my changes or different reason...
```
The command "awesome_bot README.md --allow-redirect --allow-dupe --allow 429 -w .amazonaws.com,news.ycombinator.com" exited with 1.
```

**Comment by QuinnyPig** [comment]
Nope, swagger.io had a header failure. With 1200 links or so, these things happen. The check is mainly to help us avoid bit rot!

**Comment by QuinnyPig** [comment]
@artemnikitin Thanks for the contribution-- I've made a couple of wording changes to your PR just for flow. If you're happy with them, I'll merge this in.  

Also, you're one of the first people I've seen in the wild using Device Farm. Are you on the [Open Guide Slack team](https://og-aws-slack.lexikon.io)? I'd love to ask you a few questions about your experience.

**Comment by artemnikitin** [comment]
> If you're happy with them, I'll merge this in.

I'm completely ok with it. No problem. You can merge.

> Also, you're one of the first people I've seen in the wild using Device Farm. Are you on the Open Guide Slack team? I'd love to ask you a few questions about your experience.

I had no idea about this Slack existence. I will join it and feel free to ask any questions :)

**Comment by artemnikitin** [comment]
@QuinnyPig is everything ok with pull request or something is still missing?

**Comment by QuinnyPig** [comment]
Sorry for the delay-- thanks for the commit!

**Pull request merged**
