### PR TITLE
Opsworks for Puppet Enterprise

### PR DESCRIPTION
**Pull request by QuinnyPig**
Embargo this until there's an official announcement, then check for accuracy.

Public pricing information came out, but no official go-live yet.

### CODE REVIEW

**Comment by QuinnyPig** [comment]
Closing, as this was pulled back.

**Comment by abrussak** [comment]
Looks like it was launched today (Nov 16)? https://aws.amazon.com/blogs/aws/new-aws-opsworks-for-puppet-enterprise/

**Comment by QuinnyPig** [comment]
...figures. Reopening!

**Comment by jlevy** [comment]
LGTM. I updated another link there for pricing.

**Pull request merged**
