### PR TITLE
Add initial info for AWS Certificate Manager

### PR DESCRIPTION
**Pull request by artemnikitin**
I have plans to add more info about AWS Certificate Manager later.

### CODE REVIEW

**Comment by ThanosBaskous** [comment]
Thank you for your submission, @artemnikitin - looking forward to seeing the AWS Certificate Manager getting more coverage!

Editors note: there is no topic editor for AWS Certificate Manager (yet), so I've taken a look.

LGTM - bouncing to @jlevy for a final pass.

**Comment by jlevy** [comment]
LGTM as well. Thanks!

**Comment by jlevy** [comment]
One thing we should expand going forward is clarifying when Certificate Manager is useful. You can't use it to get SSL certs if you're not using an AWS service to terminate the SSL, correct?  That's important for to clarify when this is expanded.

**Comment by artemnikitin** [comment]
> You can't use it to get SSL certs if you're not using an AWS service to terminate the SSL, correct?

Correct. I'm planning to add it to section with basic info, tips and gotchas.

**Comment by ThanosBaskous** [comment]
Great, thanks @artemnikitin - I'm looking forward to seeing it!

**Pull request merged**
