### PR TITLE
Update information on Lambda cold starts, add reference to provisioned concurrency

### PR DESCRIPTION
**Pull request by pgibson65**
includes links to cold start measures by runtime for 2018 vs 2019 as well as VPC-hosted Lambda improvements.

### CODE REVIEW

**Comment by QuinnyPig** [comment]
Do you want to include information about Provisioned Concurrency?

**Comment by pgibson65** [comment]
good idea; take a look at the most recent commit

**Comment by pgibson65** [comment]
should be ready to merge.   please let me know if you have other suggestions.

**Comment by QuinnyPig** [comment]
Thanks; merged.

**Pull request merged**
