### PR TITLE
Add cost savings tips for RDS and EC2

### PR DESCRIPTION
**Pull request by minimice**
Add cost savings tips for RDS and EC2 by using the Instance Scheduler solution

### CODE REVIEW

**Review by darigovresearch — APPROVED** [review]
Thanks @minimice for making the pull request, the link works and looks like it would provide another option for reducing costs.

Do any maintainers need anything else before merging the pull request?

**Comment by minimice** [comment]
> Thanks @minimice for making the pull request, the link works and looks like it would provide another option for reducing costs.
> 
> Do any maintainers need anything else before merging the pull request?

Hello, no nothing else is needed, feel free to merge the PR

**Comment by minimice** [comment]
Can you merge @darigovresearch ?

**Comment by darigovresearch** [comment]
@minimice don't have write access so can't merge but would be happy to if you can provide write access!

**Comment by darigovresearch** [comment]
image

**Comment by minimice** [comment]
@QuinnyPig can you help to merge this I have no write access

**Comment by QuinnyPig** [comment]
Sorry for the delay; merged in!

**Pull request merged**
