### PR TITLE
Add special topic on encryption

### PR DESCRIPTION
**Pull request by bgdnlp**
The PR is intended as a first draft, request for comments. Is it useful? Is it in the right place, should it be formatted differently?

The encryption it presents relates mostly to S3, but not only. The same process applies to other services, which is why I didn't want to link it to S3 specifically.

Is it useful?

### CODE REVIEW

**Comment by Ashex** [comment]
There's some good info here too: #308 

Biggest caveat for S3 is that cross region replication is currently only supported with SSE-S3.

**Comment by bgdnlp** [comment]
That's one of the questions, should this section be included under S3, or should it be left separate as general encryption topic and maybe referenced from S3?

Would be good to add examples for bucket policies enforcing SSE-KMS or SSE-S3, but that doesn't make sense if it's a general topic, so I left them out.

**Comment by Ashex** [comment]
Considering you're focusing on S3 encryption it would probably make more sense for it to fall under S3. 
Considering encryption in the context of AWS is usually going to be KMS perhaps the section on envelope encryption should then be moved to go under KMS?

The KMS area needs some extra love that I've been meaning to expand on so I can fill in some info on key policies and CMKs if you can create a quip document that I can contribute to.

**Comment by bgdnlp** [comment]
Turned this pull request into a Quip document. "Encryption Types" in the og-aws folder.

Should this PR be closed then?

**Comment by QuinnyPig** [comment]
Closing this PR. Also, let’s make sure that we capture the new S3 encryption stuff!

**Pull request closed without merging**
