### PR TITLE
Configure travis CI to check links

### PR DESCRIPTION
**Pull request by baynezy**
This utilises Travis CI to run the awesome_bot
ruby gem to check links in the README file. Preventing
broken links from making it into the project.

https://github.com/dkhamsing/awesome_bot

Guide to configuring Travis https://docs.travis-ci.com/user/getting-started/

### CODE REVIEW

**Comment by QuinnyPig** [comment]
This is great!

Can you break out the fixed link into a separate PR?

**Comment by baynezy** [comment]
@QuinnyPig done

**Comment by baynezy** [comment]
Do you need anything more on this?

**Comment by QuinnyPig** [comment]
This looks great. Merging. Will set up Travis separately. Thanks so much for your help!

**Pull request merged**
