### PR TITLE
Update the definition of AWS SWF

### PR DESCRIPTION
**Pull request by xethorn**
First, thanks for doing this!

Just a small update regarding SWF: SWF is not only a managed background job workflow (you have to write your own decider and your own tasks). It also stores and tracks states of each activity (defined has “events" in the workflow's "history”), which it sends to the decider and the workers. I added polyglot because at the comparison of other systems like Luigi, SWF is language agnostic. You can write the decider in one language, and write an activity in Go, and another one in python.

### CODE REVIEW

**Comment by ThanosBaskous** [comment]
lgtm. Thanks for your contribution, @xethorn!
@jlevy would you mind checking this out for final review/merge?

**Comment by jlevy** [comment]
👍 LGTM

**Comment by jlevy** [comment]
@xethorn Do you have a lot of experience with SWF? Any interest in contributing more on it?

**Comment by jlevy** [comment]
And thanks!

**Comment by mortaliorchard** [comment]
@jlevy : I'll try to. I wrote in python [Garcon](http://github.com/xethorn/garcon) which is used in production by a few companies.

**Comment by xethorn** [comment]
@jlevy : I'll try to. I wrote in python [Garcon](http://github.com/xethorn/garcon) which is used in production by a few companies.

**Pull request merged**
