### PR TITLE
Add ec2 gotcha - undocumented limit of zero for new accounts

### PR DESCRIPTION
**Pull request by rjhintz**
Document an undocumented restriction applicable to very new accounts, such as might be used in instruction.

A teacher attempting to have students use their own brand new accounts to each launch one g2 instance reported that the student launches failed because of an undocumented soft limit of zero. This may be associated with AWS trying to mitigate the use of GPU instances for Bitcoin mining, though that's speculation.

### CODE REVIEW

**Comment by ThanosBaskous** [comment]
LGTM, thanks @rjhintz! Moving over to @max-zanko for topic review.

**Comment by ThanosBaskous** [comment]
@rjhintz This is all set, thanks again. Once you resolve the conflicts, I will merge it.

**Comment by rjhintz** [comment]
@ThanosBaskous This should be ok.

**Comment by ThanosBaskous** [comment]
👍 Thanks @rjhintz!

**Pull request merged**
