### PR TITLE
remove advice of using reduced redundancy since it is deprecated

### PR DESCRIPTION
**Pull request by MichaelPereira**
This sentence was contradicting the section **S3 Reduced Redundancy and Infrequent Access** in the [s3 tips](https://github.com/open-guides/og-aws#s3-tips) section which clearly states that reduced redundancy is deprecated (https://www.quinnadvisory.com/blog/2017/4/13/reduced-redundancy-s3-is-dead)

### CODE REVIEW

**Comment by lobster1234** [comment]
Hi @MichaelPereira  - Please avoid making changes across multiple sections in a single PR.

**Comment by MichaelPereira** [comment]
@lobster1234 I removed the other unrelated changes

**Comment by lobster1234** [comment]
Thanks so much! The change looks good to me.

**Comment by ThanosBaskous** [comment]
👍 lgtm! Thanks for the submission, @MichaelPereira, and thanks for reviewing @lobster1234!

**Pull request merged**
