### PR TITLE
Alphabetise top list

### PR DESCRIPTION
**Pull request by M1ke**
Easier to read the top list and find a specific service

### CODE REVIEW

**Comment by QuinnyPig** [comment]
I like this a lot, but it does change the structure of the guide somewhat. Would appreciate others' feedback prior to merge.

**Comment by scott-cbt** [comment]
This seems like one of those changes that is so obvious after the fact, but something that people who are used to the project wouldn't think of.  I think it will make it easier for new people to find the section they want since they won't have to use find in document and can just scroll the list in order. 

As for service area vs alpha I think that adding more consistency might help with that.  Right now there is CLB, ALB, and Load Balancers as topics.  If they were all EC2 Load Balancers - Elastic [ELB], etc that would keep the three together, and make the alpha order very easy.

**Comment by salexpdx** [comment]
This seems like one of those changes that is so obvious after the fact, but something that people who are used to the project wouldn't think of. I think it will make it easier for new people to find the section they want since they won't have to use find in document and can just scroll the list in order.

As for service area vs alpha I think that adding more consistency might help with that. Right now there is CLB, ALB, and Load Balancers as topics. If they were all EC2 Load Balancers - Elastic [ELB], etc that would keep the three together, and make the alpha order very easy.

**Comment by M1ke** [comment]
@QuinnyPig @salexpdx I'm happy to do that change too if it will help. I'd suggest the same with Glacier; you can't use Glacier without s3, there's no separate interface for it, so S3 - Glacier would make more sense in the ordering, other than that some people might have heard of Glacier as a brand.

I also wonder if SES, SQS & SNS are well enough known acronyms and could be improved by noting the name - then someone who's starting to read with the question "does AWS have a message queue" gets their question answered reading the index. I believe S3 and EC2 are big enough brand names they don't need to be explained in the same way.

**Comment by M1ke** [comment]
@QuinnyPig @salexpdx any update on this? The Travis build failed but looks like it's due to something unrelated, a URL check that failed but I've not modified any URLs

**Comment by QuinnyPig** [comment]
Yeah, ignore the Travis results. I think you two are correct; if you get this to merge cleanly I'll endorse it!

**Comment by M1ke** [comment]
@QuinnyPig Have now resolved the conflict so we can merge this

**Comment by QuinnyPig** [comment]
It would seem not. One more conflict resolve, and I'll merge it!

**Comment by M1ke** [comment]
Ok I'll check it tomorrow, it was merging cleanly when I last commented but
guess other stuff has changed

**Comment by maishsk** [comment]
@M1ke we still have some conflicts - can you have a look please?

**Comment by maishsk** [comment]
@M1ke we still have some conflicts - can you have a look please?

**Comment by QuinnyPig** [comment]
Glorious! Merging.

**Comment by maishsk** [comment]
LGTM

**Pull request merged**
