### PR TITLE
Add Wavefront to metric management

### PR DESCRIPTION
**Pull request by durren**
add Wavefront to metric management

### CODE REVIEW

**Comment by ThanosBaskous** [comment]
Thank you for your submission, @durren. I'm not personally familiar with Wavefront, but see that its customer list has some big names on it. Are you affiliated with the company?

Our approach to vendor-specific changes so far has been to leave them open for community comment, so that's what I'm going to do here.

**Comment by durren** [comment]
Thanks Thanos, that sounds fine to me!

Yes, we do have some big names, and most of those big names are monitoring
their entire application stack and infrastructure on Wavefront (and they
have moved off of open source solutions, such as Graphite).

and yes, I am affiliated with the company, I'm one of the founders.

**Comment by jlevy** [comment]
Thanks @durren . We do want to include major players, but also want fairness/neutrality. If you know of other vendors or open source tools that should go on this line, that's also helpful!

Feel free to resolve conflicts so we can merge in.

**Comment by durren** [comment]
thanks, resolved

**Comment by jlevy** [comment]
Thanks @durren !

Couple related questions since you're evidently deep in the monitoring space:
- I'm wondering if we should split out a separate line, where visualization dashboards are separate from monitoring infra. Do you think that would help?
- How do you see the various players (like the ones discussed [here](http://blog.takipi.com/datadog-vs-signalfx-vs-new-relic-vs-wavefront-which-dashboard-should-you-choose/)) fitting in if we do that?
- Do you have any suggestions for #259?

Much appreciated.

**Comment by durren** [comment]
Hi Joshua, these are very good questions. As you know, all products
mentioned in that article are for monitoring -- it really depends on what
aspects of monitoring you want to divide the monitoring category by.
Datadog and New Relic are more of an infrastructure monitoring and APM
solution. They are good for environments that are generic, where you can
just plug in their agent and get generic infrastructure metrics, like cpu
load for each machine. Wavefront can do infrastructure monitoring as well,
and has many out-of-the-box solutions and integrations to get those types
of metrics (like statsd, collectd, telegraf).

However, the main difference is that Wavefront is a time series platform
that takes any type of time series data (custom metrics) and allows you to
store and query on it. People are using custom metrics because of the shift
to the cloud, which requires them to instrument their microservices and
pieces of cloud infrastructure to send custom metrics to Wavefront to know
what is actually going on with applications that are running at scale.

Wavefront allows the customer to send tons of custom metrics at a high
rate, and store them for a very long time and query on huge datasets super
quickly -- none of the others can quite do this.

https://bigpanda.io/monitoringscape/ <-- these guys divide the categories
of monitoring up pretty well. New Relic is more APM while Datadog is more
system/infrastructure monitoring. We are actually on the map (in time
series) in their latest version of this, but they have not published it
yet.

To answer the last bullet point, Cloudwatch data is complimentary to all of
these services. Many people need their cloudwatch data from aws, and these
services all have an "integration" with Cloudwatch that will pull
Cloudwatch data in and allow it to be visualized on their platform. The
reason that you'd want Cloudwatch data on the Wavefront platform is that
Wavefront allows you to keep that data for extended periods of time, query
it out faster (just try a month-long query on Cloudwatch on just a few
lines, it's painfully slow), construct queries on it that you could not do
in Cloudwatch, correlate it to other data in Wavefront, create alerts based
on it, and more.

let me know if you have any more questions!

**Comment by QuinnyPig** [comment]
I'm not really well positioned to judge the competitive landscape; can we borrow your insight for this PR, @mjulian?

**Comment by QuinnyPig** [comment]
Okay, I'm going to close this for now pending refactor. https://github.com/bigpandaio/monitoringscape is the landscape selector, now open sourced. I think that WaveFront (particularly in light of the VMware acquisition) is too much of a niche player to be a good representative sample in the same way as something such as Nagios would be. Instead of calling out individual vendors, I'd like to see a link against that project instead.

Ultimately, it just becomes way too easy for this to turn into a billboard otherwise; that's never been what the guide has been about.

**Pull request closed without merging**
