### PR TITLE
Updated table of services with Aurora for shared RDMS and CF for "build our own"

### PR DESCRIPTION
**Pull request by alexander-kalinovsky**
Changes to the table

### CODE REVIEW

**Comment by forwidur** [comment]
LGTM. There are conflicts though, could you please take a look?

Thanks a lot, @alexander-kalinovsky !

**Comment by alexander-kalinovsky** [comment]
I am not sure how you guys are managing this, but I now found later pull requests that are working on same sections and providing same information I did. So my pull request is now obsolete.

**Comment by ThanosBaskous** [comment]
Apologies, @alexander-kalinovsky - we are trying to make sure each sections is seen by the same person consistently at some point during the review process (for consistency and expertise reasons but also so that they can catch these types of issues) but in this case it fell through the cracks. It looks like PWS is still missing - if you update to just add that (or close and create a new PR with just that change) we should be able to get at least a part of your changeset in. Thanks for your contribution!

**Comment by jlevy** [comment]
@alexander-kalinovsky yes, sorry for the conflicts, but do feel free to re-file or resolve conflicts, don't want to lose each part of your contribution. Thanks!

**Comment by QuinnyPig** [comment]
Going to close this as @alexander-kalinovsky has gone quiet; please feel free to rebase and reopen!

**Pull request closed without merging**
