### PR TITLE
Break RDS into separate sections for MySQL, Aurora, and SQL Server

### PR DESCRIPTION
**Pull request by danhermann**
This should replace PR #203.

### CODE REVIEW

**Comment by AlJohri** [comment]
not sure if this is expected but I'm seeing some weird encoding issues in the diff

screen shot 2016-10-23 at 3 40 19 pm

**Comment by danhermann** [comment]
I'll take a look at those and see if I can resolve them.

**Comment by ThanosBaskous** [comment]
Thanks @danhermann - I see the same thing as @AlJohri (thanks for calling it out).

**Comment by ThanosBaskous** [comment]
Thanks for fixing those sections, @danhermann - what did you change? Had you copy and pasted into an editor with different encoding or without full unicode support? Unfortunately it looks like the problem still somehow exists with other emoji/unicode chars in the commit (ones in areas that you did not change).

**Comment by danhermann** [comment]
Retrying once more in #255.

**Comment by danhermann** [comment]
@ThanosBaskous, I'm doing this editing on a different machine than my usual dev environment and both its UTF and git setup is different than what I'm accustomed to. Fun times. :)

**Pull request closed without merging**
