### PR TITLE
- Added Sematext SPM & Logsene as CloudWatch Metrics & Logs alternatives

### PR DESCRIPTION
**Pull request by otisg**
Added references to Cloud-based monitoring and log management services from Sematext that are CloudWatch Metrics and Logs alternatives.  I work at Sematext.

### CODE REVIEW

**Comment by ThanosBaskous** [comment]
Thanks for being clear about your affiliation, @otisg.

**Comment by otisg** [comment]
No problem. :)  Any chance you can merge this, @ThanosBaskous ?

**Comment by QuinnyPig** [comment]
The challenge I have with this PR is that I've been in this space for a while-- this is the first I've ever heard of Sematex. I'm not trying to be offensive in any way here-- but is your footprint large enough to justify its inclusion in what's effectively a best practices guide?

**Comment by QuinnyPig** [comment]
Closing this pending further discussion; feel free to reopen.

**Pull request closed without merging**
