### PR TITLE
Added more details to AWS Batch Section

### PR DESCRIPTION
**Pull request by lobster1234**
Added more details based on the feedback received on slack.

### CODE REVIEW

**Comment by jlevy** [comment]
👍 Looks good. One request would be if we can add a few links to some of these items — ideally most of the bullets would have a link.

I'm good with it as is, but it should get a 2nd review from someone with more Batch expertise.

**Comment by jlevy** [comment]
And a nit: docker -> Docker throughout.

**Comment by lobster1234** [comment]
@jlevy Thanks for the feedback! I will add a few links and fix the docker vs. Docker 👍

**Comment by ThanosBaskous** [comment]
Thanks for the edits, @lobster1234!

**Pull request merged**
