### PR TITLE
Added AWS Batch Section

### PR DESCRIPTION
**Pull request by lobster1234**
Please review and provide feedback on this pull request for adding a section on AWS Batch.

### CODE REVIEW

**Comment by QuinnyPig** [comment]
This looks good to me. Thanks for the contribution. Let's wait for one more person to weigh in before we merge it.

**Comment by lobster1234** [comment]
Sounds good - thanks @QuinnyPig!

**Comment by ThanosBaskous** [comment]
LGTM - thank you for adding this section, @lobster1234!

**Comment by lobster1234** [comment]
Glad to help!

**Pull request merged**
