### PR TITLE
Fixup EFS Wording

### PR DESCRIPTION
**Pull request by QuinnyPig**
Fixed some word choices in the EFS section, renamed File Store to Object Store in the service matrix

### CODE REVIEW

**Comment by jlevy** [comment]
Cool, nice variety of cleanups. (All small, so not pulling in other editors.)

**Comment by bgdnlp** [comment]
One thing. EFS pricing is based on volume of stored data. Recursive operations like find and chown will not affect the cost directly.

**Comment by jlevy** [comment]
Oh, hm, that's right @bgdnlp — pricing doesn't include requests. @QuinnyPig what did you have in mind when you added "cost" to that sentence about find/chown?

**Comment by QuinnyPig** [comment]
Something very different. Whoops. My apologies. PR incoming.

**Pull request merged**
