### PR TITLE
adding tagging tools to the billing and cost visibility section

### PR DESCRIPTION
**Pull request by em0ney**
This change adds references to the auto-tag and retro-tag tools in the section on billing and cost visibility.

Disclaimer: I work at GorillaStack. We authored these open source tagging tools and I am adding a reference to GorillaStack later in the section in a list of relevant cost optimization tools.

### CODE REVIEW

**Comment by em0ney** [comment]
build failing with opsclarity.com unavailable

**Comment by QuinnyPig** [comment]
Looks like there are merge conflicts. It's also a bit fraught when representatives of a company highlight their offerings, regardless of whether or not they're open source; it creates an appearance of conflict of interest. :-/

**Comment by jrichard68** [comment]
I have unsubscribe from this thread a million times and have no idea how I got subscribed to it.  Please stop sending this!

On Oct 19, 2019, at 3:27 PM, Corey Quinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like there are merge conflicts. It's also a bit fraught when representatives of a company highlight their offerings, regardless of whether or not they're open source; it creates an appearance of conflict of interest. :-/

**Comment by MSohail73** [comment]
Hi There,

Pleas do the same for me as well.

Thanks,

**Comment by QuinnyPig** [comment]
...it's Github. You can adjust your GitHub notifications in your account settings, unsubscribe from the thread itself at https://github.com/open-guides/og-aws/pull/712, or unwatch the associated repository. We're not doing anything particularly fancy on this one; it's all on them!

**Pull request closed without merging**
