### PR TITLE
Added Tool for viewing AWS Billing with ELK(Elasticsearch, Logstash, Kibana)

### PR DESCRIPTION
**Pull request by droidlabour**
Forked from [ProTip/aws-elk-billing](https://github.com/ProTip/aws-elk-billing)
[PriceBoardIn/aws-elk-billing](https://github.com/PriceBoardIn/aws-elk-billing/) awaits to be merged.

### CODE REVIEW

**Comment by jlevy** [comment]
Thanks for the contribution.

Do want to note that you are affiliated with the tool you're listing. There's nothing wrong with that, but we do ask people to disclose relevant affiliations in the PR. https://github.com/open-guides/og-aws/blob/master/CONTRIBUTING.md#pull-request-etiquette

Do you have any data on how widely used this tool is or what others like it exist? Also, what's the difference between the PriceBoardIn and ProTip forks?

Would like to get some feedback/review from other ELK folks too, as I don't have extensive experience. Thanks again!

**Comment by droidlabour** [comment]
The main difference between the PriceBoardIn and ProTip forks is The overall installation process is made easy with Docker and some default ELK visualisation are added.

**Comment by jlevy** [comment]
I know this has been a while. It seems like a useful tool — I'd just like to see us put a little time into listing the variety of top, current useful tools for cost visibility, not just this one. I think there are a few new ones we're missing. Let's see if we can get a list formulated in Slack and then merge this along with some other items.

**Comment by QuinnyPig** [comment]
Closing for now, pending the outcome of the Slack discussion. The costing space is both small and crowded; I'm unconvinced that listing every project here makes sense.

**Pull request closed without merging**
