### PR TITLE
added links to Lambda code samples

### PR DESCRIPTION
**Pull request by lynnlangit**
from my 'big link list'

### CODE REVIEW

**Comment by ThanosBaskous** [comment]
lgtm - thanks @lynnlangit!

Assigning @ehammond for topic review.

**Comment by ehammond** [comment]
LGTM

**Comment by lynnlangit** [comment]
Anything else for me to do here?

**Comment by jlevy** [comment]
LGTM too. Just a couple copy editing details, but I'll make them myself.

**Comment by jlevy** [comment]
Thanks!!

**Comment by ThanosBaskous** [comment]
Thanks @lynnlangit!

**Pull request merged**
